// Copyright(c) 2025, Bohdan Soproniuk
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#version 450

#extension GL_EXT_buffer_reference : require

layout(local_size_x_id = 0) in;
layout(constant_id = 1) const uint count = 0;
layout(constant_id = 2) const uint length_ = 0;

const uint base1 = 33;
const uint base2 = 209;
const uint mod1 = 65521;
const uint mod2 = 16777213;

struct Hash
{
    uint id;
    uint hash1;
    uint hash2;
};

layout(buffer_reference, std430) readonly buffer SymbolBuffer
{
    uint symbols[];
};

layout(buffer_reference, std430) readonly buffer HashBuffer
{
    Hash hashes[];
};

layout(buffer_reference, std430) buffer ResultBuffer
{
    uint result;
};

layout(push_constant) uniform ReferenceBlock
{
    SymbolBuffer sb;
    HashBuffer hb;
    ResultBuffer rb;
};

int binarySearch(uint hash1, uint hash2)
{
    int lo = 0;
    int hi = int(count) - 1;
    while (lo != hi)
    {
        int mid = lo + (hi - lo + 1) / 2;
        if (hb.hashes[mid].hash1 > hash1 ||
            (hb.hashes[mid].hash1 == hash1 && hb.hashes[mid].hash2 > hash2))
        {
            hi = mid - 1;
        }
        else
        {
            lo = mid;
        }
    }
    if (hb.hashes[lo].hash1 == hash1 && hb.hashes[hi].hash2 == hash2)
    {
        return lo;
    }
    return -1;
}

void main()
{
    const uint id = gl_GlobalInvocationID.x;
    if (id < count)
    {
        if (id == 0)
        {
            atomicExchange(rb.result, 0);
        }
        uint coeff1 = base1;
        uint coeff2 = 1;
        for (uint i = 0; i < length_; ++i)
        {
            int sign = sb.symbols[hb.hashes[id].id * length_ + i] == 1 ? 1 : -1;
            uint hash1 = (hb.hashes[id].hash1 + sign * coeff1 + mod1) % mod1;
            uint hash2 = (hb.hashes[id].hash2 + sign * coeff2 + mod2) % mod2;
            int j = binarySearch(hash1, hash2);
            while (j >= 0)
            {
                if (!(hb.hashes[j].hash1 == hash1 && hb.hashes[j].hash2 == hash2))
                {
                    break;
                }
                if (hb.hashes[id].id < hb.hashes[j].id)
                {
                    atomicAdd(rb.result, 1);
                }
                --j;
            }
            coeff1 = coeff1 * base1 % mod1;
            coeff2 = coeff2 * base2 % mod2;
        }
    }
}